# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            María José Mora Luque
tagline:          ''
description:      'Farmacéutica. Especialista en deshabituación tabáquica. Máster en Tabaquismo; Máster en Promoción de la Salud y Apoyo Psicosocial al Paciente.'
url:              http://www.mjmora.es
baseurl:          /

author:
  name:           'Ricardo Garcia'
  url:            https://twitter.com/rjgarciam

paginate:         3

# Custom vars
version:          0.8.0

github:
  repo:           https://github.com/rjgarciam/mjmora
